[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
spl_utils = "B96dV3Luxzo6SokJx3xt8i5y8Mb7HRR6Eec8hCjJDT69"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
